[features]
seeds = true
skip-lint = false
[programs.localnet]
pooled_die = "3kNw5Q6SaTEmtX64HtHtjbNFfytxfLn8wALCdYQfFQhP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]] # programID
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # idlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # programState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # tokenWallet
address = "BVFBmA8qdrEx5JAsrMSX4NFEPNTcDWCzNiTia3ezsQyB"

[[test.validator.clone]] # queue
address = "CXfXJSXt7ZLPtRAKsmRstKc8TvmGhyqFMNsuLQoy8Sqz"

[[test.validator.clone]] # queueAuthority
address = "7meYik28Tqe74npkJjbW9jrbeUPXPZ6jfMrLoxT8E9Pn"

[[test.validator.clone]] # queueBuffer
address = "H6JTPYRnjADxptV8p2Nr1NKTqauyJR5hrffXLCqjAz1d"

[[test.validator.clone]] # crank
address = "2V1hQLbbSJdMS4hhmMtFotEqHru1sKmp2s8RwdcFcAwG"

[[test.validator.clone]] # crankBuffer
address = "6HDYJHR1KTo29cxzMqc9A9rcjgEbG6aByPtQPqRxwV2u"

[[test.validator.clone]] # oracle
address = "BkHh4zfACbvf1GNjk2F6EuXzEKiJVkyX4hyZD31arCpp"

[[test.validator.clone]] # oracleAuthority
address = "7meYik28Tqe74npkJjbW9jrbeUPXPZ6jfMrLoxT8E9Pn"

[[test.validator.clone]] # oracleEscrow
address = "2kfPMbZEfit4QJY9Hd82Zh5cSPWi6fc8cF8gHupH3Qcs"

[[test.validator.clone]] # oraclePermissions
address = "4XsMQPRXiqgqRYwhvTH4vEpjdpCwgeVyBDc9S77HcT1y"
